### PR TITLE
offense.txt

### PR DESCRIPTION
**Pull request by afos2**
These are tables and columns for the breakdown of offensive stats.
t_id = team id
p_id = player id
game_id = ... if you don't know this one, then leave.

### CODE REVIEW

**Comment by matthewjwolff** [comment]
Some of the columns seem like calculations based on other columns. For example, yards/attempt is easiliy calculated by actually performing the division. I mean we could have those precalculated in the table already, but that might be something we actually do as part of the project? Like make a SQL query that calculates that?

**Comment by matthewjwolff** [comment]
If we're ok with doing that, then :+1: from me

**Comment by matthewjwolff** [comment]
Also I'm guessing we'll merge in with :+1: from me and @cowhiz25 ?

**Comment by afos2** [comment]
Yes, that was the plan to either display it as a calculation (x/y) as STAT when we show the tables, or use it in a separate SQL query

**Comment by matthewjwolff** [comment]
Okey. Let's make a note of those options.

**Comment by afos2** [comment]
Noted.

**Comment by sdoiron25** [comment]
👍 from me

**Pull request merged**
